
all:
	javac *.java

boot:
	java BootstrapNameServer configs/bnConfigFile.txt

name1:
	java NameServer configs/nsConfigFile1.txt

name2:
	java NameServer configs/nsConfigFile2.txt

name3:
	java NameServer configs/nsConfigFile3.txt

name4:
	java NameServer configs/nsConfigFile4.txt

name5:
	java NameServer configs/nsConfigFile5.txt

clean:
	rm -f *.class

